const router = require('express').Router()
const renderDoc = require('../../renderDoc')

router.get('/aboriginal', (req, res) => {renderDoc(req,res,'1m07P6Lrl_WOh3_jG_wSX3yyDcmVEpf15QRNa0westT8')})
router.get('/ancient-history', (req, res) => {renderDoc(req,res,'17LnO9Rqt_4arFwY6w6uGejTWEHvZjW-6YqpSuiSAddY')})
router.get('/biology', (req, res) => {renderDoc(req,res,'17SpGKBxh9QP7cthsRaUsj_zG0oy5Gmmp0OgHF8zU0TY')})
router.get('/business-studies', (req, res) => {renderDoc(req,res,'1eV6c8MUC4Ufq3vMPw5oml9ph_HPBj68vXtcMOu-l2tY')})
router.get('/cafs', (req, res) => {renderDoc(req,res,'1iYL408i4vEGRWuB1PJyghLWxqnOPWf1Hsm2PhR2_P1M')})
router.get('/chemistry', (req, res) => {renderDoc(req,res,'1se0hLvHhtnXJaAmn7UUmljH361jdMcsk-kn6IGJzqc4')})
router.get('/design-tech', (req, res) => {renderDoc(req,res,'112a8i7t96mKB0gHJJPFskVBXJoOa5l0gZSqPP7elu_Q')})
router.get('/drama', (req, res) => {renderDoc(req,res,'152i3KPpTeeZVG8COa14-Mp27HlJxUG0nRgiFMhMyNQw')})
router.get('/english', (req, res) => {renderDoc(req,res,'166HXxYqK5f5xe6m2diuu03TYr3CAOpUUxlew4zNEYAc')})
router.get('/film-vid', (req, res) => {renderDoc(req,res,'1EU23a13J4oClcSQOdqC_xNyT5DYGEtq2Te6BXDlP4Qw')})
router.get('/hospitality', (req, res) => {renderDoc(req,res,'1GSZjKsxbYA4-LUFe7NLXFO4DLVkFsr0vRo8g895j4dw')})
router.get('/industrial-technology', (req, res) => {renderDoc(req,res,'1_IjkvbJfi5zzaziC4SQfQtsIXI82wne5IdBkvVTNUEU')})
router.get('/legal-studies', (req, res) => {renderDoc(req,res,'1ci1b3vIp50DN8zYvt32Fr6gcVp0r305u3QQDG-cUKTo')})
router.get('/marine-studies', (req, res) => {renderDoc(req,res,'1iscizmjNCJsTevB5Ts_7DembDxpoaD0HbAeIN5b9aHs')})
router.get('/mathematics', (req, res) => {renderDoc(req,res,'1r8o1LvCccCAeO1cdPlrtEWpNlf6zht5YWnn92QNIkao')})
router.get('/modern-history', (req, res) => {renderDoc(req,res,'1tQhBpR-bj2WHuPWxyA6DNZN3PM3XPXPcI5KcyE1rGp4')})
router.get('/music', (req, res) => {renderDoc(req,res,'1--aXnp7dLbxqnufjMCSmehbBndMQlh9eAutsrxR-XKM')})
router.get('/pdhpe', (req, res) => {renderDoc(req,res,'1-w4rmE1uXfodoQ2dc8C1MINw1NoIvxY1dyfMe62MEw4')})
router.get('/physics', (req, res) => {renderDoc(req,res,'16LwmWUKmyTQB9J49v65NtDrD7FEvcYEuNbPth_7MNms')})
router.get('/sdd', (req, res) => {renderDoc(req,res,'17o00ahyFb-KHECXYBEjhQfIjKnih7fqkK2tGOpKjk24')})
router.get('/slr', (req, res) => {renderDoc(req,res,'1CDqURgrT5UbHSLi8qpybXFUCnjqgbepeV0ntnLqu8Wo')})
router.get('/society-culture', (req, res) => {renderDoc(req,res,'1FIk6c6kHt1eDPTItTfBwrWZKmR-WDgENvNFlZVwQpzM')})
router.get('/visual-arts', (req, res) => {renderDoc(req,res,'1QKSLLWssIDBzPDXtd0C_wX7p9j_vEmQsg2fqGgGMW74')})

module.exports = router
